In [5]:
import pandas as pd

In [8]:
covid_df=pd.read_csv("balaji_data.csv")

In [9]:
type(covid_df)

pandas.core.frame.DataFrame

In [10]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2020-03-01     122958        6029     128541
1    2020-03-02     147867       14428     179083
2    2020-03-03     132932       17517     151027
3    2020-03-04     366838        3105     134531
4    2020-03-05     260178        4627     108712
..          ...        ...         ...        ...
895  2022-08-13     231907       16251     150408
896  2022-08-14     291160        1526     143950
897  2022-08-15      24960        4224     156849
898  2022-08-16     296735       16069     128044
899  2022-08-17     214920       12536     115997

[900 rows x 4 columns]

In [ ]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        20 non-null     object
 1   new_cases   20 non-null     int64
 2   new_deaths  20 non-null     int64
 3   new_tests   20 non-null     int64
dtypes: int64(3), object(1)
memory usage: 772.0+ bytes

In [11]:
covid_df.describe()

           new_cases    new_deaths      new_tests
count     900.000000    900.000000     900.000000
mean   242889.466667  10475.174444  150786.337778
std    145044.389223   5403.384092   28442.189986
min      2542.000000   1009.000000  100163.000000
25%    120162.250000   5839.500000  126986.250000
50%    228355.500000  10335.000000  150088.500000
75%    369139.250000  14997.250000  174671.250000
max    499863.000000  19988.000000  199983.000000

In [12]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

THIS IS THE INTRODUCTION TO PANDAS PYTHON WHERE THE ITS INTITAL KNOW AS PANDAS ALIALS PD AND THE OPERATING FUNTIONS ARE .INFO() AND .DESCRIBE() GIVES THE KNOW AND THE STD MIN,MEAN ,MEDAIN INFORMATION ABOUT THE META  DATA ABOUT WHICH WE KNOW 
                                       -BALAJI BHAGIRATH BODDUCHERLA

In [14]:
#how to access to specfic index of the value
covid_df["new_cases"][261]

np.int64(336674)

In [16]:
#this gives the total number of new_cases and new_deaths passed due to covid and there sum
total_cases=covid_df.new_cases.sum()
print(total_cases)
total_deaths=covid_df.new_deaths.sum()
print(total_deaths)

218600520
9427657

In [18]:
high_cases=covid_df.new_cases>100000
print(high_cases)

0       True
1       True
2       True
3       True
4       True
       ...
895     True
896     True
897    False
898     True
899     True
Name: new_cases, Length: 900, dtype: bool

In [19]:
covid_df[high_cases]

           date  new_cases  new_deaths  new_tests
0    2020-03-01     122958        6029     128541
1    2020-03-02     147867       14428     179083
2    2020-03-03     132932       17517     151027
3    2020-03-04     366838        3105     134531
4    2020-03-05     260178        4627     108712
..          ...        ...         ...        ...
894  2022-08-12     493734       13091     137643
895  2022-08-13     231907       16251     150408
896  2022-08-14     291160        1526     143950
898  2022-08-16     296735       16069     128044
899  2022-08-17     214920       12536     115997

[717 rows x 4 columns]